project:
  type: website
  output-dir: docs

website:
  title: "Methods, Virology & More"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume_may_25_en.pdf
        text: CV
        target: _blank
  page-footer: 
    left: "Copyright 2025, James R. Hunter"



format:
  html:
    theme: lumen 
    css: styles.css
    toc: true
    


