project:
  type: website
  output-dir: docs

website:
  title: "Methods, Virology & More"
  navbar:
    logo: media/jrh logo.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd # listing page for blog
      - href: resume_may_25_en.pdf
        text: CV
        target: _blank
  page-footer: 
    left: "Copyright 2025, James R. Hunter"



format:
  html:
    theme: 
      - lumen
      - styles.scss 
    mainfont: Nunito
    toc: false
    


